version: "3.7"

services:
    botadmin:
        container_name: botadmin
        build: ./app
        networks:
            - bot_network
        env_file:
            - .env

networks:
    bot_network:
        driver: bridge
volumes:
    postgresql_data:
        driver: local
